# A version catalog file for declaring versions of various dependencies used in the project.
#
# To reference anything in this file, use:
# - the `libs.plugins.<whatever>` notation to access the version information of a plugin;
# - the `libs.bundles.<whatever>` notation to access the version information of a bundle of dependcies; and
# - the `libs.<whatever>` notation to access the version information of a library dependency.

# Version declarations that can be used in the `version.ref` property in the upcoming declaration
# of libraries, bundles and plugins.
[versions]
# The Discord IPC library version the project depends on.
discord-ipc = "0.2.2"
# The Documentation library for kotlin.
dokka = "1.9.10"
# The Fabric API version the project depends on.
fabric-api = "0.91.0+1.20.1"
# The Fabric Language Kotlin adapter the project depends on.
fabric-language-kotlin = "1.10.14+kotlin.1.9.20"
# The Fabric Loader version the project depends on.+++
fabric-loader = "0.15.6"
# The Fabric Loom version used by the project.
fabric-loom = "1.5.7"
# The memory optimazation mod.
fabric-ferrite-core = "6.0.1-fabric"
# Rendering API For Fabric.
indium = "1.0.25+mc1.20.1"
# The Shader Mod Iris
iris = "1.6.7+1.20.1"
# The Kotlin version used by the project.
kotlin = "1.9.10"
# The Kotlinx Coroutines version the project depends on.
kotlinx-coroutines = "1.7.3"
# The Log4J version the project depends on.
log4j = "2.22.1"
# The Minecraft version used targeted at by the project.
minecraft = "1.20.1"
# The sodium mod version  + minecraft version.
sodium = "mc1.20.1-0.5.2"
# Adds extras to sodium.
sodium-extra = "mc1.20.1-0.5.1"
# The Yarn mappings used by the project.
yarn = "1.20.1+build.10"

# Libraries used by the project.
[libraries]
discord-ipc = { module = "com.github.caoimhebyrne:KDiscordIPC", version.ref = "discord-ipc" }
dokka-base = {module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka"}
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-ferritecore = { module = "maven.modrinth:ferrite-core", version.ref = "fabric-ferrite-core"}
indium = { module = "maven.modrinth:indium", version.ref = "indium"}
iris = {module = "maven.modrinth:iris", version.ref = "iris"}
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium"}
sodium-extra = { module = "maven.modrinth:sodium-extra", version.ref = "sodium-extra"}
yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }

# Bundles of libraries used by the project.
#
# Used to avoid declaring a collection of libraries multiple times across the monorepository.
[bundles]

# Plugins used by the project.
[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = {id = "org.jetbrains.dokka", version.ref = "dokka"}